### ISSUE TITLE
hows the google seo for this site ?  |   Shall i go ahead and use vue.js fo my production app that needs SEO as top priority ?

### ISSUE THREAD

**Issue by jpca999** [vuejs/vue-hackernews-2.0#128]
I tried to search for how much google has cached, but turns out it hasn't that much.  
 site:https://vue-hn.now.sh/

Any explanation for this ?

Basically what i m looking is should I be scarred to use this in production  or not for my project that depends highly on SEO.  ?

**Comment by Smallpath** [comment]
That's just because it didn't provide `sitemap.xml` to the google spider, not because of SSR not working. Generating sitemap isn't the role which SSR plays.

In addition, even if you don't use SSR for your vue project ,  google can still send cached it correctly. Many search engine spider support running javascript, and google is one of them

**Comment by yyx990803** [comment]
SEO is a much bigger topic, SSR is only a part of it. This demo is only about SSR, it doesn't do anything else for SEO.
