### ISSUE TITLE
How does this app implemented as a real time app? plus what is SSR in "    // this will be called during SSR to pre-fetch data into the store! "

### ISSUE THREAD

**Issue by zzz6519003** [vuejs/vue-hackernews-2.0#20]

**Comment by LinusBorg** [comment]
Hello @zzz6519003 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
