### ISSUE TITLE
Unit testing and integration tests

### ISSUE THREAD

**Issue by silvestreh** [vuejs/vue-hackernews-2.0#42]
Would be really cool to see examples on how to do proper testing of Vue components and Vuex stores, mutations, and actions 😄

**Comment by elliotlarson** [comment]
I agree.  I'm just starting out with Vue.js.  I think the documentation and examples for Vue are pretty fantastic.  Clearly a ton of work has gone into both, and they've made it possible to get up and running with Vue quickly.  However, I like to test drive most of the code I write; partly because I like the TDD process, but also because I feel like it's a great way to learn.  It would be awesome to have some more guidance from the core team on how they test the various part of a Vue app.

**Comment by mimani** [comment]
+1

**Comment by thulioph** [comment]
+1

**Comment by balibou** [comment]
+1

**Comment by ruben-podadera** [comment]
+1

**Comment by itumoraes** [comment]
+1

**Comment by jbuget** [comment]
+1

**Comment by silvestreh** [comment]
Don't hold your breath fellas. This seems to either be outside of the scope for this demo or super low priority, which I'd understand if any of those is the case.

To all collaborators: keep up the good work, Vue's awesome! ❤️

**Comment by john-ko** [comment]
theres [vue-cli](https://github.com/vuejs/vue-cli). if you run the demo project, you can build it with unit  (karma) and e2e (nightwatch) tests

**Comment by liron-navon** [comment]
@silvestreh @elliotlarson @john-ko @mimani 

Hey, I wrote an article for my company's blog about writing tests for vue applications and setting up CI, I know It's a lot of changes for a single PR, but if you want you could merge these.
They include a few unit tests, e2e tests, and snapshot tests, and set up for CircleCI.
Unfortunately, I had a hard time mocking firebase in this project's setup 😥.

https://github.com/vuejs/vue-hackernews-2.0/pull/355
