### ISSUE TITLE
The client-side rendered virtual DOM tree is not matching server-rendered content.

### ISSUE THREAD

**Issue by tronghiep92** [vuejs/vue-hackernews-2.0#45]
Hi ,
I saw an error like this
[![Screenshot from 2016-10-17 16:13:07.jpg](https://s21.postimg.org/4sf851513/Screenshot_from_2016_10_17_16_13_07.jpg)](https://postimg.org/image/ghj7szvzn/)

**Comment by LinusBorg** [comment]
Please provide some information.

...what did you do to mak this happen? Did you change anything or did you run the original code?

If the latter, on what node version is the server running? What Browser did you use?

**Comment by tronghiep92** [comment]
@LinusBorg I think so firebase  automatically updated realtime.
Run ```npm run dev``` and wait about two minutes, refresh page.

**Comment by nateajohnson** [comment]
I am getting this error on a fresh install. It doesn't happen on first load, but just doing a full refresh in the browser and I get this error in dev tools. Anyone find a solution?

**Comment by nateajohnson** [comment]
Also, I only see this error when running in dev mode. Production seems to be fine.

**Comment by richardcarls** [comment]
I have this issue on my current Vue project (I'm using the "prefetch" methods approach shown here for SSR). It looks like Vuex actions are invoked on initial render, but then we get this error because the actions haven't commited state yet, so our vdom list is empty compared to the server-rendered html.

I don't see how they are supposed to match, so wondering why there is a warning for this at all. Also wondering if hydration is scrapped for the entire app or just this particular component, and if the former, does it do this in production?

**Comment by i-akhmadullin** [comment]
Seems like store don't use state from `window.__INITIAL_STATE__` so it's always starts on client-side with default/empty state: https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/store/index.js#L8

So to fix this issue store should be initialized on client side with state from ```window.__INITIAL_STATE__```:
```js
const store = new Vuex.Store({
  state: inBrowser ? window.__INITIAL_STATE__ : serverState,
  ...
```

**Comment by corner1990** [comment]
I also encountered this problem, how do you solve the problem?

**Comment by amritk** [comment]
I also have this issue when rendering elements whose if statements are coming from a vuex getter

**Comment by amritk** [comment]
nvm just saw this @corner1990 
https://github.com/vuejs/vuex/issues/877
