### ISSUE TITLE
Use Element UI ----> ReferenceError: window is not defined

### ISSUE THREAD

**Issue by stchou** [vuejs/vue-hackernews-2.0#69]
@yyx990803 

project base on hacknews

Use the eleme UI （element ui）,  add code on app.js
```
import Vue from 'vue'
import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'
import App from './App.vue'

Vue.use(ElementUI)

new Vue({
  el: '#app',
  render: h => h(App)
})
```
but something wrong with it

```
ReferenceError: window is not defined
```

It's the server side rending cause it?

**Comment by stchou** [comment]
I resolve it，thanks

**Comment by yuchonghua** [comment]
How do you solve it? Easy to teach me about it

**Comment by mamboer** [comment]
how?

**Comment by bmarkovic** [comment]
@stchou It would be nice if you would tell what was wrong and how you solve it so that others facing the same issue could use your findings at least as a hint. Closing the issue without explaining how you solved the error is horrible ettiquette and against the spirit of open source. Community gave you Vue, give back!

**Comment by zhump** [comment]
@stchou 确实不厚道。。
webpack.base.config.js 中 配置css-loader
```
  {
            test: /\.css$/, 
            loader: ["vue-style-loader", "css-loader"]
   },
```

**Comment by FlyPointRed** [comment]
app.js 中 加入 
![image](https://cloud.githubusercontent.com/assets/15316874/25948344/9e327164-3685-11e7-9b91-5ac16820c675.png)
element ui就在项目中运行正常了
